export const LESSON_LEVELS = [
  "A1",
  "A1-A2",
  "A2",
  "A2-B1",
  "B1",
  "B1-B2",
  "B2",
  "B2-C1",
  "C1",
] as const;

export type LessonLevel = (typeof LESSON_LEVELS)[number];

export type LessonCategory = "grammar" | "vocabulary" | "seasonal" | "unavailable";

export type LessonDefinition = {
  title: string;
  category?: LessonCategory;
};

const lessonCategoryOrder: LessonCategory[] = ["grammar", "vocabulary", "seasonal", "unavailable"];

const lessonGroups: Record<LessonLevel, (string | LessonDefinition)[]> = {
  A1: [
    { title: "A Night in the Clouds (Past Simple)", category: "grammar" },
    { title: "Amazing Autumn Days (Questions words)", category: "grammar" },
    { title: "Are You Ready To Order?", category: "vocabulary" },
    { title: "Big City, Small Town - Opposite Adjectives", category: "unavailable" },
    { title: "Common Irregular Verbs (Past Simple: irregular verbs 20)", category: "grammar" },
    { title: "Everyday Small Talk", category: "vocabulary" },
    { title: "Family Connections (Possessive 's)", category: "grammar" },
    { title: "Famous Faces Uncovered (Present Simple to be +, -, ?)", category: "grammar" },
    { title: "Father's Day", category: "seasonal" },
    { title: "Find It in the House (Prepositions of Place)", category: "grammar" },
    { title: "First Trip Together", category: "vocabulary" },
    { title: "Health Problems", category: "unavailable" },
    { title: "In My Childhood (Past Simple: Regular Verbs)", category: "grammar" },
    { title: "It Is Study Time", category: "unavailable" },
    { title: "It Was a Nice Weekend (Past Simple to be: was/were)", category: "grammar" },
    { title: "Let Us Get Started - First Lesson (be vs have got)", category: "grammar" },
    { title: "Making Requests In Everyday Situations (can/could for requests)", category: "grammar" },
    { title: "Meet the Housemates", category: "unavailable" },
    { title: "Most Common Irregular Verbs (Past Simple: irregular verbs 40)", category: "grammar" },
    { title: "My Day on Repeat", category: "unavailable" },
    { title: "My Day, My Way (Present Simple to do)", category: "grammar" },
    { title: "New Faces, New Stories", category: "unavailable" },
    { title: "Nice to Meet You", category: "unavailable" },
    { title: "Our Small Traditions", category: "unavailable" },
    { title: "Packing For A Trip (prepositions of place in, on, at)", category: "grammar" },
    { title: "People and Their Things (Possessive Pronouns)", category: "grammar" },
    { title: "People, Things, and Pronouns", category: "unavailable" },
    { title: "Red Flag, Green Flag: You Decide", category: "unavailable" },
    { title: "Say Hello to the World", category: "vocabulary" },
    { title: "She Can Do That", category: "seasonal" },
    { title: "Spring Picnics", category: "seasonal" },
    { title: "Summer vs Autumn - Back on Track Series", category: "seasonal" },
    { title: "The Advice Line", category: "unavailable" },
    { title: "The Best Christmas Tree Ever", category: "seasonal" },
    { title: "The Code of Daily Life", category: "grammar" },
    { title: "The Golden Tastes of Autumn", category: "seasonal" },
    { title: "The Secret Language of Cats", category: "vocabulary" },
    { title: "This or These (Demonstrative Pronouns)", category: "grammar" },
    { title: "Weather Wonders", category: "vocabulary" },
    { title: "What Can You Do", category: "unavailable" },
    { title: "What Did You Do Last Weekend? (Past Simple: irregular verbs 20)", category: "grammar" },
    { title: "What Is In Your Fridge? (there is, some/any, countable/uncountable)", category: "grammar" },
    { title: "What Shall We Do?", category: "unavailable" },
  ],
  "A1-A2": [
    "A Very Simple Apartment Tour",
    "Valentine's Day Memories",
    "Amazing Stories of Amazing Women",
    "Exploring the City",
    "Easter Egg Traditions Around the World",
    "Talking About Outfits",
    "Shop Like a Pro",
    "From Pan to Plate (Cooking Vocabulary)",
    "Summer Staycation Ideas",
    "Fun Ways to Look at Your Future: true or not? Future Simple",
    "Exploring the Jobs",
    "Marvels of Nature (Degrees of Comparison)",
    "City Life (Present Continuous)",
    "Amazing Autumn Days",
    "Boo-tiful Halloween",
    "Everyday Things",
    "Happy Thanksgiving Day",
    "Black Friday Is Coming",
    "The Best Christmas Tree Ever",
    "New Year, New Habits",
    "Making Requests In Everyday Situations",
    "Lovely Spring Ideas",
    "What about Shopping?",
    "Get To Know Your Emotions",
    "Mother's Day mini-lesson",
    "Step by Step (would like/love to)",
    "Father's Day",
    "Summer Picnic Essentials. Question Words",
    "Box, Bag, and Beyond (Containers)",
    "Apartment Hunting (Rent a Flat)",
    "Have You Ever? (present perfect)",
    "Welcome to My Sims House",
    "Doggie Discoveries",
    "Creepy Carnival Adventure Genially Quest",
    "Black Friday: Think Twice!",
    "A Day for Saint Nicholas",
    "Where Winter Meets Cosy",
    "The Polar Express to Christmas Genial.ly Quest",
    "Wrap It Up! The gift Guide",
    "The Rhythm of Free Time - Adverbs of Frequency",
    "Tastes of the Streets",
    "Gifts! Yay or No Way?",
    "What is on Your Tongue?",
    "The Way of Living",
    "She Did It First",
    "Spring Survival Guide",
    "Shamrocks, Leprechauns, and Luck",
    "Time to Pack and Plan - Be Going To",
    "London Unlocked",
    "What Is In My Beach Bag?",
    "Bucket List: Summer Edition",
    "Summer Fashion Battle",
    "How Much Is Too Much",
    "Off to the Theme Park",
    "Summer vs Autumn - Back on Track Series",
    "Say Hello to the World",
    "My Daily Vibes - Present Simple",
    "Living City Moments - Present Continuous",
    "The Hotel of Forgotten Guests",
    "The Golden Tastes of Autumn",
    "Through the Street Window",
    "Letters of the Christmas Hour",
    "Mini Goals: Tiny Steps to Success",
    "Winter Travel Adventures",
    "Valentine's Day Is More Than Hearts",
    "The First Hot Days",
  ],
  A2: [
    "10 Weirdest Houses",
    "All About Thanksgiving",
    "Breakfasts Around the World",
    "Christmas Is Fun!",
    "The World's Most Unusual Cafes",
    "Ridiculous Sports",
    "Staying Healthy (Modal Verbs)",
    "School Adventures",
    "Summer Chronicles",
    "What Is The Hardest Instrument To Learn",
    "I Would Like To Order (Passive Voice)",
    "At the Cinema",
    "Winter Holiday Destinations",
    "Tell Me A Story (Past Continuous and Past Simple)",
    "The Great Easter Egg Hunt",
    "That Is My Plan First Conditional",
    "What Is Your Perfect Hobby? Present Simple and Present Progressive",
    "A2 Revision Lesson",
    "Friendly Pets (Adverbs of Manner)",
    "Getting To Know You - First Lesson",
    "Veganism As A Lifestyle",
    "A Trip to the Salon",
    "Beyond the Steering Wheel",
    "At the Beauty Lounge",
    "A Very Ukrainian Christmas",
    "Holiday Escapes - Gerund and Infinitive",
    "Everyday Things 2.0",
    "Fix It Up",
    "Her Side of the Story",
    "There Is Nothing In The Fridge - Indefinite Pronouns",
    "Life When I Was a Child - Used to",
    "Discover Your Personality Type",
    "All by Myself",
    "Around the Neighbourhood",
    "Minimalist vs. Maximalist Lifestyles",
    "Home Life With Flatmates",
    "What Can I Do at Home Modal Verbs Can/Have to",
    "Healthy Habits and Lifestyle Choices - First Conditional",
    "Secret Santa",
    "What Do You Read",
    "Women Support Women",
    "Modern Men, Modern Women",
    "Spring Colours and Outfits",
    "My Career Path Now, Next, Later - Will vs Be Going to",
    "Let's Get Nails Done",
    "Always Busy, Never Productive",
    "On Your Own Around The World",
    "Less Phone, More Life",
    "Getting Ready For An Interview",
    "Check In, Speak Up",
    "Are You a Sleep Maxer",
    "Beat the Sunday Scaries",
    "Let's Go Out! - Phrasal Verbs with Up",
    "The Perfect Place to Work",
    "Online Drama, Real Problems",
    "Have You Ever Watched It",
  ],
  "A2-B1": [
    "Silly Inventions",
    "Could You Travel The World Without Flying?",
    "What would happen if humans disappeared?",
    "Unusual Jobs",
    "Winter Bucket Lists",
    "Personality and Temperament Types",
    "Hobbies that would surely surprise you",
    "Unique Valentine's Day Traditions",
    "Saving and Spending",
    "Let's Talk About Future - Future Forms",
    "Natural Beauty Routine",
    "Never Have I Ever",
    "Crimes and Criminals",
    "Crazy Hotels Around The World",
    "Happy Birthday (Special Edition)",
    "Mysteries of Saint Nick",
    "The Secret Santa Agency Quest (Online)",
    "Mirror, Mirror, Tell Me More",
    "Inside a Concert (Stative Verbs)",
    "How to Survive a Tsunami (Natural Disasters)",
    "The World Around Me (Order of Adjectives)",
    "Happy Mother's Day (mini-lesson)",
    "Airport Adventures",
    "A Day For Dad",
    "Digital World (either, neither, both)",
    "Welcome to China (Culture Shock Pack)",
    "Brazil As It Is (Culture Shock Pack)",
    "Norwegian Adventures (Culture Shock Pack)",
    "Welcome to South Korea (Culture Shock Pack)",
    "From Bonnet to Boot",
    "Dancing With Dragons",
    "Understanding AI",
    "Millionaire Madness",
    "Spring-Cleaning... Your Digital Life",
    "Pysanky. Symbols, Stories, and Shells",
    "Keep Calm and BBQ On",
    "Burning Man - Summer Festivals Bundle",
    "Ivana Kupala - Summer Festivals Bundle",
    "La Tomatina - Summer Festivals Bundle",
    "Notting Hill Carnival - Summer Festivals",
    "Summer Solstice Celebrations - Summer Festivals Bundle",
    "A Chat With Your Inner Child",
    "Marketing Magic",
    "Mess Mode Activated - so and such",
    "One Summer, One Lesson - Back on Track Series",
    "Everyday Superstitions",
    "When Life Hacks Go Wrong",
    "The Sharing Economy in Daily Life",
    "The Haunted Clock Tower",
    "The Rise of Third Places",
    "Cosy Days of Autumn",
    "The Kind Story Klaus",
    "Winter Mystery Inn Genial.ly Quest",
    "The Big Year Wrap-Up!",
    "From Holidays Back to Routine",
    "Do the Stars Match?",
    "A2-B1 Friendship When You're An Adult - Speaking Club",
    "This Summer Will Be Different",
    "The Household Ghost",
    "Money In, Money Out",
    "Run Clubs",
    "Life on Two Wheels",
    "When Plans Go Wrong - Gerunds and Infinitives 2.0",
  ],
  B1: [
    "A Snapshot Of My Life - First Lesson",
    "Four Steps to Making a New Friend (Phrasal Verbs)",
    "Mood Matters",
    "Why Do We Gossip",
    "Cooking Can Be Fun",
    "The Art of Delegation (Have Something Done/Causative)",
    "Renting an Apartment (Rent a Flat)",
    "The World Awaits",
    "No Money, No Honey",
    "The Art of Vlogging",
    "The Power Of Regret (I wish, If only)",
    "Evolving Coffee Culture. Ordering Coffee",
    "Exploring the Olympic Games",
    "Begin With The Stars",
    "Autumn In A Big City",
    "Race to the White House",
    "From Challenge To Change - Prefixes",
    "Singles' Day (mini-lesson)",
    "The Art of Solo Dates",
    "Not All Pink And Pretty",
    "Missed Trains and Lost Chances - Third Conditional",
    "Everyday Phrasal Verbs",
    "No-Buy Challenge",
    "Becoming a Meme by Mistake",
    "Too Hot to Handle",
    "The Perfect Sleep Vacation",
    "Behind the News - Articles",
    "Discover Ukraine: Nature and Wildlife",
    "Young Hands, Big Impact - Reported Speech",
    "Rules Are Made to Follow - Passive Voice",
    "The History of Photography",
    "University Life",
    "Home Emergencies",
    "Crime Stories in the News",
    "Unwritten Rules of Life",
    "Do or Make?",
    "The Journey of Life",
    "Never Have I Ever 2.0 Present Perfect vs Past Simple",
    "Hobbies Aren't fun Anymore",
    "Best Side Hustles To Do",
    "Then vs Now: Ukrainian Winter Traditions",
    "The Art of Christmas Ads",
    "Where Has Winter Gone",
    "Sorry, Could You Help Me?",
    "Meeting Basics",
    "Love Isn't Just Romance",
    "Plans vs Reality Future Forms",
    "Behind the mask",
    "Thrift Shopping And Special Trips",
    "Ups And Downs At Work",
    "People Who Changed The World - Relative Clauses",
    "Easter Brunch Ideas",
    "First Job Interview",
    "Online vs Offline - Opinion Paragraph",
    "Excuse Me, Is This Art?",
    "Group Chat Chaos - Adjectives Ending in -ed and -ing",
    "Which Holiday Sounds Better? - Comparative and Superlative Forms",
    "To Post or Not to Post - Gerund and Infinitive",
    "The Joy of Guilty Pleasures",
    "Ever Needed One of These?",
    "Still Watching, Aren't You? - Tag Questions",
    "Ukraine's Independence Day",
  ],
  "B1-B2": [
    "A Brief History of Emoji",
    "American Thanksgiving",
    "Hidden Meanings of Famous Logos",
    "Christmas Ads",
    "How do you use social media?",
    "What is your earliest childhood memory?",
    "Tiny Slang Song. American and British Slang",
    "Women in Science Who Changed the World",
    "We Need a Bigger Definition of Creativity (Reported Speech)",
    "Unexpected Facts About Easter",
    "How to Break Habits",
    "What If You Met a Time Traveller? (Present and Past Tenses Revision)",
    "Minimalist Cleaning and Tidying Routine",
    "Dog Days Of Summer (Summer Idioms)",
    "Gym Tips for Beginners (Vocabulary and Speaking)",
    "Stages of Life",
    "Romanticising Autumn",
    "Extreme Experiences",
    "Halloween Online Quest (Genially)",
    "Foods of the Future",
    "All You Need Is Love",
    "The Frenzy of Black Friday",
    "The Quirky World of Ugly Christmas Sweaters",
    "New Year's Luck",
    "Fancy a Cuppa?",
    "Reading Tastes",
    "Happily Ever After",
    "Festival Fever",
    "Jolly Good Talk. British Slang",
    "Friendsgiving Fusion",
    "Exploring Winter Aesthetics",
    "Christmas at Hogwarts",
    "Love at First Date",
    "Stay Active And Be Healthy",
    "What Is Eating You?",
    "Building Better Workspaces Modals",
    "Perfecting New Skills - Present Perfect Simple Present Perfect Continuous",
    "No Valentine, Galentine",
    "Hop the Globe",
    "Everyday Eco-Habits",
    "From Boomers to Alphas",
    "Spotlight on Eurovision",
    "Summer Up with Phrasal Verbs",
    "Discover Ukraine: Sport heroes",
    "B1-B2 Home Emergencies",
    "Discover Ukraine: Future Made by Ukrainians",
    "Paw-rents Unite",
    "Discover Ukraine: Icons of Design",
    "The House That Thinks",
    "Holiday Stories Remix",
    "Discover Ukraine: Folk Magic",
    "Snow, Love, Cliches",
    "B1-B2 The Final Countdown - Stranger Things Season 5",
    "Behavioural Economics",
    "Clear Memories And Meaningful Moments Narrative Tenses",
    "Digital Hearts, Real Feelings",
    "B1-B2 Behind the mask",
    "B1-B2 The Unspoken Rules",
    "Discover Ukraine: Famous & Ukrainian",
    "The Price of Summer",
    "Summer Love On Screen",
    "Renting Forever: Dream or Trap?",
    "The Night of Falling Stars",
    "The Trouble Next Door",
    "Quiet Vacationing",
    "The Little Treat Economy",
  ],
  B2: [
    "Personality and Character Idioms",
    "The Greatest Mysteries of the World",
    "Who is Banksy? Modern Street Art",
    "All You Need To Know About Christmas",
    "Cashless Society",
    "Love in the Digital Age",
    "5 Reasons Why AI Can't Replace Humans",
    "What Multitasking Does to Your Brain?",
    "How to tell if someone is lying to you",
    "First Impressions",
    "Exploring Urban Legends",
    "How to Be Uncool and Not Care What People Think",
    "Judge a Book by Its Cover",
    "The Art of Privacy in the Digital Age",
    "At The Art Museum",
    "How to Boost Your Productivity",
    "Habits to Follow for a Better Work-Life Balance",
    "What Is An Attractive City?",
    "Seven Perks Of Being Quiet",
    "Write It For Me",
    "FOBO (Fear of Better Options)",
    "7 Ways to Cultivate Self-Love",
    "Spring Outfit Ideas",
    "Bizarre Laws Decoded",
    "Pick Me, Boss Babe & Beyond",
    "Procrastination Nation",
    "What Are Your Glimmers?",
    "How To Spot Fake News",
    "Apple Vision Pro",
    "Comfort and Annoyance. Would rather. Had better",
    "Zoom Fatigue (and idioms to talk about it)",
    "Slow Living",
    "Why We Remember and Forget - Memory Idioms",
    "Perfect Gift-Giving Formula",
    "Winter Arc Challenge",
    "New Year, Old Me (30+ minutes)",
    "Tailoring Your CV",
    "Love Languages",
    "Tiny Bricks, Big Ideas",
    "The Art of Craftsmanship",
    "Women Who Made It",
    "Spring Minimalist Challenge",
    "Is Spring Fever Real?",
    "Your Dream Garden",
    "Breaking the Atmosphere",
    "Most Memorable Easter Tradition",
    "The Comfort Food Fix",
    "Summer Burnout",
    "Unbelievable Travel Stories - Inversion",
    "Wedding Bells Worldwide",
    "Vacation or Workation",
    "Dopamine Rush: Scrolling, Snacking, Streaming",
    "Ink or Think - Getting a Dream Tattoo",
    "Digital Detox",
    "How Long Can You Keep the Summer Version of You - Back on Track Series",
    "Stretch and Shine",
    "Life Choices - Mixed Conditionals",
    "The Science of Better Living",
    "The Librarian's Last Watch",
    "The Year-End Wrap-Up!",
    "Building The Future - Future Perfect VS Future Perfect Continuous",
    "The Illusion of Objectivity",
    "Dress codes at Work - Base Cohesion in Essay Writing",
    "Ageing As A Woman",
    "Places People Live In",
    "A Moment in Life - Stylistic Devices",
    "Life Stories - Narrative Tenses",
    "What They Don't Tell You About Pregnancy",
    "All Eyes On The Met",
    "Ikigai: Your Reason to Get Up",
    "How To Be A Good Leader",
    "Romanticising Your Life",
    "My Story So Far - Present Perfect Simple & Continuous",
    "I Should Have Known Better - Perfect Modals",
    "Your Brain Can Improve at Any Age",
    "Travel Tales - Writing a Travel Blog Post",
    "Life, Unscripted",
    "Cringe-Worthy Moments",
  ],
  "B2-C1": [
    "Medical myths or facts?",
    "The Future of Gaming",
    "The Secret of the Manhattan Christmas Quest (Online)",
    "Tips to Keep Your New Year's Resolutions",
    "Are You Google Affected?",
    "The Spotlight Effect",
    "Travel Trends That Will Shape This Year",
    "The Art of Small Talk - First Lesson",
    "AI in Education - Hero or Threat",
    "Moving Abroad Is No Longer The Dream?",
    "Should You Trust Your Gut Feeling?",
    "Will AI Make Decisions Instead Of Us?",
    "The Awe Effect: Why Beauty Makes Us Better",
    "Is Your Brain Lying to You?",
    "Plot Twists and What Ifs - All Conditionals Revision",
    "Admin Nights - Speaking Club",
    "Friendflation",
    "The Age of AI Slop",
    "The Vibe Economy",
  ],
  C1: [
    "What Is Sonder? Phrases for speculating",
    "Unusual Startups",
    "It Is All About the Mood (Autumn)",
    "This Is Halloween",
    "Thanksgiving For Everyone",
    "Winter Self-Care",
    "Astrological Forecast",
    "English. The Comedy Edition.",
    "From Posts to Paychecks",
    "Reinventing Yourself After a Break - Back on Track Series",
    "Greenwashing vs. Real Sustainability",
    "The Economy of Attention",
    "When Smells Speak",
    "Asian Tiger",
    "The Future of Work",
    "The Gold Economy",
    "The Illusion of Savings",
    "The World Ahead",
    "Do You Get Deja Vu?",
    "Nature As Therapy",
    "Why Can't We Stop Collecting?",
    "Main Character Energy",
    "Impostor Syndrome: Bug or Feature?",
    "City Summer: A Sensory Portrait",
    "Letter To My Younger Self - Wishes and Regrets",
    "The Business of Stress",
    "The Cool Hunter",
    "Decision Fatigue",
    "Table for Two - Writing a Review",
    "Big News, Big Feelings - Idioms",
    "The Ethics of Nostalgia",
  ],
};

export const LESSON_LIBRARY = LESSON_LEVELS.flatMap((level) =>
  lessonGroups[level].map((lesson) => {
    const definition = typeof lesson === "string" ? { title: lesson } : lesson;
    return {
      level,
      ...definition,
      key: `${level}:${definition.title}`,
    };
  }),
);

export function getLessonsByLevel() {
  return LESSON_LEVELS.map((level) => ({
    level,
    lessons: LESSON_LIBRARY
      .filter((lesson) => lesson.level === level)
      .sort((first, second) => {
        const firstCategory = first.category ? lessonCategoryOrder.indexOf(first.category) : -1;
        const secondCategory = second.category ? lessonCategoryOrder.indexOf(second.category) : -1;
        return firstCategory - secondCategory;
      }),
  }));
}